### ISSUE TITLE
Fix CodeLand Metadata Issue

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#101]
# Description of Task

It appears that when `CodeLand` is searched on Google, our website comes up at the top (yay!) but the title of the site is labeled as `CodeLand 2021` instead of `CodeLand 2022`. Hoping this is something @danieltott can help us fix 😊 

## Definition of Done

When CodeLand appears in search engines, our CodeLand marketing site should be titled `CodeLand 2022` instead of `CodeLand 2021`

### Screenshots/Examples
![metadata bug](https://user-images.githubusercontent.com/69541346/164286305-1812e7a6-7015-4a63-aa6c-6767a24a2def.png)

**Comment by danieltott** [comment]
@SGGregory So this is Google showing a cached version of the title (and it only happens on mobile google, desktop shows the correct title). You can request this to be updated through Google Analytics - I don't have access to the codeland GA account, but whoever does can follow the directions here: http://labs.seoclick.com/request-outdated-cache-removal-google.html
