### ISSUE TITLE
Update Website for Tracy Chou Announcement 

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#106]
# Description of Task

We're announcing another CodeLand speaker on May 10, 2022 around 9:30 AM PT

We would like to feature Tracy Chou on the site following the announcement in the ways described below. 

### Add Tracy Chou to headlining speakers section:
- [ ] Add Tracy Chou headshot underneath Kelsey Hightower's. Headshot file [here](https://user-images.githubusercontent.com/69541346/167476952-d9548767-6830-4906-b2b5-3b1b2705fa5c.jpg).
- [ ] Add name `Tracy Chou` to the right of the headshot.
- [ ] Beneath name, add the following copy: `Tracy Chou is an entrepreneur and software engineer known for her work advocating for diversity and inclusion in tech. She is currently the founder and CEO of Block Party, which builds tools for online safety and anti-harassment.`

### Add a small banner or popup at the top of the site linking to our Tracy Chou announcement post

- [ ]  Text should say: 

- [Heading] Tracy Chou Has Been Announced as a Speaker at CodeLand 2022!
- [sub-heading/C2A, italicized] Learn more [here] {link to be provided}.

## Requested deadline

Tuesday, May 10, around 9:30 AM PT.

**Comment by danieltott** [comment]
@SGGregory this is all set pending getting the live link. Deploy preview here: https://deploy-preview-107--codelandconf.netlify.app/

**Comment by SGGregory** [comment]
Awesome @danieltott! Here's the live link for the top banner: https://community.codenewbie.org/codenewbie/tracy-chou-to-speak-at-codeland-2022-3e5f

**Comment by danieltott** [comment]
@SGGregory this is live!
