### ISSUE TITLE
Remove Shubhendra Singh Chauhan from marketing site

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#112]
This speaker will no longer be joining us at CodeLand so we'll want to remove them from the site as soon as possible. Thank you!

**Comment by abbyphoenix** [comment]
Closed via a new upload of the talks2022.json file [here](https://github.com/code-newbies/codeland/tree/main/data). 

[The site](https://codelandconf.com/#program) should now be up to date!
