### ISSUE TITLE
Update Tracy P Holmes' bio on marketing site

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#114]
Tracy changed employers and will need her bio updated on the site to the following...

`A "jackie of all trades" (and mistress of being herself), Tracy is a Technical Community Advocate at Isovalent focusing on all things Cilium, eBPF, and Anxiety Driven Development. When she isn't leveling up her programming skills, hanging with her pup, or learning all she can about the next "Something-OPS", she likes helping others have "lightbulb" moments. Tracy is active in the open source community and is a strong believer that open source is like gardening - pay attention to your conditions, and water only when needed.`

Thank you!

**Comment by abbyphoenix** [comment]
Emailed Tracy to get a shorter bio, because it needs to be 500 characters (including spaces) and is currently 528. Will update this as soon as she sends that!

**Comment by abbyphoenix** [comment]
[Updated](https://codelandconf.com/#program) now with a shorter bio that reflects Tracy's new job:

`A "jackie of all trades" (and mistress of being herself), Tracy is a Technical Community Advocate at Isovalent focusing on all things Cilium, eBPF, and Anxiety Driven Development. When she isn't leveling up her programming skills, baking, or learning about the next "SomethingOps", she likes helping others have "lightbulb" moments. Tracy is active in the open source community and strongly believes open source is like gardening - pay attention to your conditions, and water only when needed.`
