### ISSUE TITLE
Update Silvia's name on marketing site

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#115]
Just heard from our speaker Silvia that she'd like her name changed on the site and wherever we mention her name. 

Can we change it on the site from Silvia España Gil to `Silvia España` (i.e. dropping the "Gil")? 

Tagging @abbyphoenix in case this is something that can be edited on our side of things. 

Thank you!

**Comment by abbyphoenix** [comment]
[Updated](https://codelandconf.com/#program) in her name and in her bio!
