### ISSUE TITLE
Add Sponsor footer

### ISSUE THREAD

**Issue by abbyphoenix** [code-newbies/codeland#116]
Please create a Sponsor footer at the bottom of the page. Ideally it'd be under the CodeLand 2022 logo, and then we could change the copy to say: 

"Brought to you by Forem and the below Sponsors"

And then we put it above the Sponsorship and Contact boxes.

It should feature the logos and links for all Sponsors in the Airtable under Content Dash. Patron Sponsor should come first and be bigger, the rest can all be the same size and can follow the order listed in the Airtable.

**Comment by abbyphoenix** [comment]
Okay, after conversation in Slack, discard the above, haha.

So here's what we'd like instead:

- Change the top nav label for **Sponsorship** to be **Sponsors**
- In that section, remove all current content and instead, replace it with:

### CodeLand 2022 Sponsors

The Patron Sponsors
All other Sponsors

In the order and with the logo & link listed in the Content Dash tab (Web - Sponsors view) in Airtable.

**Comment by abbyphoenix** [comment]
Oh, and in the style of what's currently at the [day-of site](https://community.codenewbie.org/codeland-test-2022), ideally. Thank you!

**Comment by danieltott** [comment]
@abbyphoenix here's a deploy preview: https://deploy-preview-117--codelandconf.netlify.app/#sponsors

**Comment by abbyphoenix** [comment]
Looks great!

Okay, @danieltott -- we're ready to publish this live with the information in the [Airtable](https://airtable.com/invite/l?inviteId=inv6NIYKOq6KVPM3N&inviteToken=e1f6c835699804efa1d2b8073cc278c1d7f24b1193303d593fa75e643d11ab4f&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts) -> CodeLand Content Dash tab -> Web - Sponsors view. 

Everyone except AWS for now, in the order listed there. Thank you!

**Comment by abbyphoenix** [comment]
Can we update this one last time, now that our final Sponsor (AWS) has finally been approved? Their logo, blurb, and link are in the Airtable now.

**Comment by abbyphoenix** [comment]
@danieltott taking my first breather time during CodeLand Day 1 to resurface this -- thanks!!

**Comment by danieltott** [comment]
@abbyphoenix sorry - will get on that right now

**Comment by danieltott** [comment]
@abbyphoenix live 👍🏼
