### ISSUE TITLE
Small problem with speakers grid on main page

### ISSUE THREAD

**Issue by nhampton-ut** [code-newbies/codeland#2]
I was looking at the site in excited anticipation of this summer's conf while walking across the street to pick up some tacos, so I was on my phone. I noticed that the names in the speaker boxes were causing some sizing irregularities in the box heights, and that the right margins were based on an nth-child scheme that broke when the grid went from 4-per-row to 3-per-row. Looked like small mistakes I would miss while building our code challenge frontend at work.

I would have forgot about it, but I was talking to my wife a few days later, who's also excited to come to the conf and learning Node currently. She was getting down about her amazing design (https://toniagonzalez-expressportfoliosite.glitch.me/, looking for work) when I said the best of us miss things, and remembered the small mistake on your site. It made her feel a lot better and excited for the conf!

But enough dorking out, I wanted to say you should have:
```
.speaker .speaker-title {
   min-height: 72px;
}
.speaker:nth-child(3n) {
   margin-right: 0;
}
.speaker:nth-child(4n) {
   margin: 2.35%;
}
@media only screen and (min-width: 700px) {
   .speaker .speaker-title {
      min-height: 72px;
   }
}
@media only screen and (min-width: 900px) {
   .speaker .speaker-title {
      min-height: 120px;
   }
   .speaker:nth-child(3n) {
      margin-right: 2.35%;
   }
   .speaker:nth-child(4n) {
      margin: 0;
   }
}
```
...or something like that somehow in your sass. That fixed it for my screen I think, but not when I tried to work it into the css cascade, so some fitting is necessary. Katrina Owen is a good example to watch for the nth-child margin issue, and Norah Klintberg Sakal is defining the minimum height needed. Rock on, love everything Code Newbie is doing, big fans over here!

- Nic Hampton

**Comment by nickytonline** [comment]
@danieltott, the site has been redesigned since this was logged, so this may no longer be an issue..
