### ISSUE TITLE
Update copy on site to reflect CFP open

### ISSUE THREAD

**Issue by abbyphoenix** [code-newbies/codeland#48]
#### Details

The CFP opens today (June 22), and we should update [the site](https://codelandconf.com) to reflect that, by:

- Under **Attend** -> **Important Dates**: add [this link](https://cfp.codelandconf.com/events/codeland-2021) to this text "Call-For-Proposals (CFP) opens"
- Under **Submit a talk**: remove the second paragraph and replace it with "Our [Call for Proposals (CFP)](https://cfp.codelandconf.com/events/codeland-2021) is open now! It closes on July 22, so be sure to submit your ideas for great CodeLand talks before then."

#### Deadline

Can we have these changes done by 11:30am PT / 2:30pm ET today (June 22)? Please confirm in the #codeland-2021 Slack channel when they're done. Thank you!!

**Comment by emmmmmmmmmmmma** [comment]
[Updated!](https://github.com/code-newbies/codeland/commit/f27e18f66f727d131e7e2b8f981b9dd4b7408dee) @abbyphoenix 

#48 f27e18f

**Comment by abbyphoenix** [comment]
I'm so sorry to do this so soon, but I totally caught a typo I made (that I _knew_ I'd make at some point, sigh): it should be "closes on July 20," not July 22 under **Submit a talk**.

**Comment by emmmmmmmmmmmma** [comment]
~~Ahh, just saw this -- lemme make the change real quick.~~

Done! 021a604
