### ISSUE TITLE
Remove `<hr>` element from list of important dates

### ISSUE THREAD

**Issue by aitchiss** [code-newbies/codeland#53]
The "list of important dates" at the bottom of the home page is correctly contained within a `ul` element, but unfortunately, [screen readers will not be able to announce these items](https://dequeuniversity.com/rules/axe/4.2/list?application=AxeChrome) as a list because the inner markup contains elements that aren't list items.

We should remove the `hr` element from the list itself - there are a few ways to do it, but the simplest might be to bring it inside the first `<li>` item

**Comment by emmmmmmmmmmmma** [comment]
@aitchiss Would removing the `hr` element and adding a border to the list items in the CSS work for this?

**Comment by aitchiss** [comment]
Hey @emmmmmmmmmmmma yep that should work perfectly 👍
