### ISSUE TITLE
Close CFP

### ISSUE THREAD

**Issue by abbyphoenix** [code-newbies/codeland#55]
As the CFP closes today (at 11:59pm UTC / 7:59pm ET / 4:59pm PT), we should remove reference to it being open on the site. 

**Important Dates**

- Leave text but remove link to "Call-For-Proposals (CFP) Opens"

**Submit a Talk**

- Remove second paragraph and replace with: "Our Call for Proposals (CFP) has now closed. We're now hard at work reviewing proposals to craft a fantastic CodeLand 2021 program! If you submitted a proposal, we'll be getting back to you by **August 17**."

**Comment by abbyphoenix** [comment]
@emmmmmmmmmmmma -- forgot to tag you, sorry!

**Comment by emmmmmmmmmmmma** [comment]
Should I wait to push this at 11:59 UTC? @abbyphoenix

**Comment by abbyphoenix** [comment]
@emmmmmmmmmmmma It was 11:59 UTC yesterday, so nope, as soon as you can works! ;)

**Comment by emmmmmmmmmmmma** [comment]
Completed with 36039a2 (forgot to comment this last week!)
