### ISSUE TITLE
Consider hosting the site on Netlify

### ISSUE THREAD

**Issue by danieltott** [code-newbies/codeland#59]
Since DEV already has a netlify account - I think this is a low-effort/high-reward move. 

The biggest thing hosting on Netlify will give us is [deploy previews](https://docs.netlify.com/site-deploys/deploy-previews/) - automatically-built hosted versions of sites when pushing PRs etc - there's literally no way to preview changes without pulling the site down and building locally. [Here's a list](https://www.netlify.com/github-pages-vs-netlify/) of other benefits. 

It will take maybe 10 minutes to get the site up on netlify, and then all that would need to happen is someone can switch the DNS, which I can assist with as well.

Tagging @nickytonline @joshpuetz for comments

**Comment by nickytonline** [comment]
I think this makes a lot of sense. I would be down to getting this set up once all the high priority Codeland issues are sorted.

Thoughts @pkfrank @Zhao-Andy  since you hold the keys to the Netlify account.

**Comment by Zhao-Andy** [comment]
I think Netlify is a good option -- happy to set this up on the Forem Netlify account. I'll defer the final decision to whoever is best for that (not me haha).

Right now, deployment seems tied to GitHub Pages. @danieltott I'm guessing there might be some additional setup needed to make it work with Netlify? It probably wouldn't be many steps, but if you want to make a branch I can start to demo a website vai Netlify off this repo and that branch.

**Comment by danieltott** [comment]
@Zhao-Andy It should just work - netlify will auto-detect the middleman settings. I can make a branch do things like removing the github gem thing and updating the docs, but I don't think we'll need to make any changes to actually get the build to go on netlify if we want to test it out. The build command is `bundle exec middleman build` - and it seems (unless I'm missing something) like it's using standard/default middleman settings.

**Comment by danieltott** [comment]
@Zhao-Andy actually it seems like I might be able to do it on the DEV account if you'd like me to give it a shot...

**Comment by danieltott** [comment]
![image](https://user-images.githubusercontent.com/360261/128724487-27851b75-27b7-4969-ac73-3de8ab8c2afe.png)

**Comment by Zhao-Andy** [comment]
Nice, looks great! Go for it :)

**Comment by danieltott** [comment]
OK - so this is a pretty funky netlify situation, but it looks like I was able to _create_ the site, but now I can't _access_ it 🤦 

If someone can add me to that site (right now I'm only on forem.com) - that would be wonderful and I can finish setting it up 😄 

It'll have a weird auto-generated name right now, first step will be re-naming it.

**Comment by danieltott** [comment]
CC above comment @Zhao-Andy - not sure if you're the one with those permissions - thanks!

**Comment by Zhao-Andy** [comment]
Hey @danieltott, sorry that's not me unfortunately! I believe @pkfrank or @benhalpern can do that.

**Comment by danieltott** [comment]
OK great - @pkfrank was able to get me in.

The site looks good: https://codelandconf.netlify.app/

The next steps would be (in order):

1. Update the DNS to point to netlify
2. remove gh actions and other gh pages stuff from the current site

The DNS settings would be:

```
codelandconf.com A 75.2.60.5
www CNAME codelandconf.netlify.app.
```

No idea who would be in charge of DNS stuff, but changing those two DNS records will change the site over to netlify 👍 

In the meantime we can already use the deploy previews, so we got that going for us, which is nice.

**Comment by danieltott** [comment]
@nickytonline This seems to be working pretty well and now that we're not in crunch time I think we can move forward. Who should we talk to about changing the DNS settings?

**Comment by nickytonline** [comment]
@Zhao-Andy, would you happen to know who we can talk to about making the DNS change to that we can point to Netlify for serving the live site?

**Comment by Zhao-Andy** [comment]
Hmm probably @benhalpern or @pkfrank is my guess.

**Comment by pkfrank** [comment]
@Zhao-Andy I have access to update the CodeLandConf DNS.  Can we confirm whether there's any "timing" considerations to be aware of (IE should I hold off on changing records until we're ready to take some other actions)?

Best way to catch me during working hours will be to DM me via Slack.

**Comment by Zhao-Andy** [comment]
I think the worst case scenario is 24 hours. Do we have any edge caching available with Codeland? If so that might help mitigate the changes, but IMO this is a rip off the bandage situation. My experience with Netlify has been that the DNS gets picked up quickly.

I'll leave this for @danieltott and @nickytonline to finalize since I'm more of a messenger than a project owner here.

**Comment by danieltott** [comment]
@pkfrank we're in good shape for the DNS change this week - there aren't a lot of incoming changes right now while we prepare internally for the day-off stuff. I confirmed our settings are correct on the netlify side, so we're good to go!

If you can send me a message when you do the transfer, I'll make sure it all happens smoothly, set up let's encrypt, etc. 

Let me know if you have any questions!

**Comment by danieltott** [comment]
Since this is a static site it's a pretty low-pressure DNS change.

**Comment by danieltott** [comment]
@Zhao-Andy @pkfrank Hey all! I'm back for codeland 2022! It looks like we never pulled the trigger on changing the DNS for this to point to netlify. Would it be possible to do this this week?

Here's the notes from Netlify (you can also check this out [at the netlify domain config](https://app.netlify.com/sites/codelandconf/settings/domain):

## codelandconf.com
> 
> ### Recommended:
> **Point ALIAS, ANAME, or flattened CNAME record to apex-loadbalancer.netlify.com**
> 
> If your [DNS provider supports ALIAS, ANAME, or flattened CNAME records](https://answers.netlify.com/t/support-guide-which-are-some-good-dns-providers-for-alias-aname-support/211), use this recommended configuration, which is more resilient than the fallback option.
> 
> Create an ALIAS, ANAME, or flattened CNAME record for codelandconf.com pointing to our load balancer at apex-loadbalancer.netlify.com.
> 
> ```
> codelandconf.com ALIAS apex-loadbalancer.netlify.com
> ```
> 
> ### Fallback:
> **Point A record to 75.2.60.5**
> 
> If your DNS provider does not support ALIAS, ANAME, or flattened CNAME records, use this fallback option.
> 
> Create an A record for codelandconf.com pointing to our load balancer’s IP address 75.2.60.5.
> 
> ```
> codelandconf.com A 75.2.60.5
> ```
> 
> Warning! With your current configuration of this apex domain being your primary custom domain, you won’t benefit from the full advantages of a CDN.


### www.codelandconf.com
> 
> ### Point www CNAME record to codelandconf.netlify.app
> 
> Log in to the account you have with your DNS provider, and add a CNAME record for www pointing to codelandconf.netlify.app.
> 
> ```
> www CNAME codelandconf.netlify.app.
> ```

**Comment by danieltott** [comment]
All set - thank you @Zhao-Andy!
