### ISSUE TITLE
Allow pages to set title/meta info

### ISSUE THREAD

**Issue by danieltott** [code-newbies/codeland#60]
Currently `<title>` and all other meta data is hard-coded in `layout.erb`: 

https://github.com/code-newbies/codeland/blob/98a5c7cbc1ac123dd707062199ea672d219089a8/source/layouts/layout.erb#L8-L41

### Proposed solution:
Add title and anything else we'd like to change per-page to pages' [front matter](https://middlemanapp.com/basics/frontmatter/), then update our layout file to use that.

**Comment by danieltott** [comment]
### [Home](https://codelandconf.com/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/accessibility](https://codelandconf.com/accessibility/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/faq](https://codelandconf.com/faq/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/coc](https://codelandconf.com/coc/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/coc](https://codelandconf.com/coc/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/privacy](https://codelandconf.com/privacy/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

### [/terms](https://codelandconf.com/terms/)
**Title:** CodeLand Conference 2021
**Description:** The most welcoming conference for early-career coders and their champions.

**Comment by SGGregory** [comment]
@danieltott I went off of the tabs I saw on the Netlify preview and also added in the pages you list above. 

### Home

**Title:** CodeLand Conference 2021
**Description:** CodeLand is a virtual tech conference for early-career coders by CodeNewbie & DEV.to: two software communities built on Forem. September 23-24, 2021.

### Attend

**Title:** CodeLand 2021 Registration & Pricing
**Description:** CodeLand 2021 registration is open! Join us for two remote days of live keynotes, on-demand talks, & interactive add-on workshops. Tickets starting at $0.

### Program

**Title:** CodeLand 2021 Program/Agenda
**Description:** Live keynotes & on-demand talks from inspiring speakers across the CodeNewbie & DEV.to community. Find out who’s speaking at the CodeLand 2021 conference.  

### Sponsors

**Title:** CodeLand 2021 Sponsorship Info
**Description:** Become a sponsor of the CodeLand 2021 event to support a community of early-career software developers & get your product in front of a global tech audience. 

### Accessibility

**Title:** CodeLand 2021 Accessibility 
**Description:** Read CodeNewbie & DEV’s a11y statement to discover how captioning, talk recordings, & a focus on inclusivity will make CodeLand 2021 accessibility-first.  

### FAQs

**Title:** CodeLand 2021 FAQs
**Description:** Q&A about CodeLand 2021. Learn where the event will take place, our target audience, & accessibility at our conference.


### Code of Conduct  

**Title:** CodeLand 2021 Code of Conduct
**Description:** Required conduct for all speakers, sponsors, and attendees of CodeLand 2021. 

### Terms

**Title:** CodeLand 2021 Terms of Service
**Description:** Compliance information, use license, disclaimers, and terms for CodeLand 2021. 

### Privacy

**Title:** CodeLand 2021 Privacy Policy
**Description:** The CodeLand 2021 Privacy Policy explains your privacy rights and how we will use and store your personal information.
