### ISSUE TITLE
Update site with 2021 conference program

### ISSUE THREAD

**Issue by emmmmmmmmmmmma** [code-newbies/codeland#66]
In advance of registration opening next Tuesday (8/17), there are some changes that need to be made on codelandconf.com:

- The CFP/"Submit a Talk" section should be replaced with the 2021 conference program. [I've already swapped in the 2020 program here,](https://github.com/code-newbies/codeland/pull/65) the data just needs to be updated (either by manually copy pasting it or by updating the `.yml` files in the repo). Abby can export the data from this year's CFP (I think in `.json`).
- The current program layout needs to be redesigned a little:
  - The headers that previously distinguished talks/workshops by day (eg: "Talks - Thursday, July 23") should instead indicate the track theme a talk falls under (eg: "Early Career Confidence") 
  - Keynote speakers should be visually distinct from the other scheduled talks; I think we'll plan to keep the speaker photos only for the keynotes
  - The remaining talks should have title, name, and bio only (no photo or talk abstract), for example:

> EARLY-CAREER CONFIDENCE
>
> The Cost of Data
> Vaidehi Joshi
> Vaidehi Joshi is…
> 
> Machine Learning on the Edge
> Sangeetha KP
> A Software Developer, an Author and a Speaker…

- The registration section under "Attend" should just be updated with a call to action/link to registration (still waiting on this).

I can help with styling and rearranging the template, but don't have the experience to work with the YAML files, image sizing, or resolving a11y issues in this section. Let me know!

**Comment by emmmmmmmmmmmma** [comment]
@danieltott I'm not sure how to approach grouping talks by their theme. The template I'm repurposing from last year (`source/layouts/_distributed_program.erb`) just loops through all the speaker data and creates HTML elements for each talk, only checking if the talk is a keynote or not. I guess this is contingent on what the 2021 data looks like, but if it's similar to the 2020 data, it would be kind of tricky to generate headers

**Comment by abbyphoenix** [comment]
So I can export a JSON file, which identifies the theme as "Track" -- does that help?

As there are only 16 of these, I'm wondering whether it's easier to just ignore the track though and hard-code in the data vs. continuously loading it in from the JSON? We had talked about that yesterday -- I'm going to send the JSON anyway, but just a heads up that this is far from final, and we'll have edits to make on the content from now through next Monday, I'm guessing. But providing it so that you have the general form to work with!

SO! I tried to include it here but it's not a supported file type, hah. So look for it in Slack, @danieltott and @emmmmmmmmmmmma!

**Comment by SGGregory** [comment]
@danieltott [here](https://docs.google.com/spreadsheets/d/1cZhwoL5d7297gJor-CHDIHhpw9vtxzjoPkyDyr3xOZg/edit?usp=sharing) is the info for the keynotes! As I mentioned in the comments, a few things are still unconfirmed but this should work as a placeholder. I'll let you know what gets updated as soon as possible!

**Comment by danieltott** [comment]
Keynote data: 


One Rule to Rule Them All: Learning in Public
Gift Egwuenu
Frontend Consultant
Passionate People
https://airtable.com/tblnTXSXkz3aKqGsC/viwFUEjQhp6juAwPj/rec1hep7tOuYjGAc1?blocks=hide
Gift Egwuenu is a frontend consultant at Passionate People and a content creator based in Haarlem Netherlands, She loves engaging with and advocating for open and inclusive developer communities and loves sharing her knowledge and experience by creating tech content for developers.

Musical Lessons for Engineering Teams: Developing a Culture of Feedback Cycles
Helen Sandi
Director of Open Source Initiatives, WordPress Lead Developer
10up
https://airtable.com/tblnTXSXkz3aKqGsC/viwFUEjQhp6juAwPj/recw6n1iuedEo8fSe?blocks=hide
Helen Sandi is the Director of Open Source Initiatives at 10up and a Lead Developer for the WordPress open source software project, now powering more than 40% of the web. From her start as a PHP/MySQL applications developer to focusing on "the front-end of the back-end" from both the development and UX perspectives, she has a knack for figuring out what people need to get things done on their websites, including most recently on the relaunch of WhiteHouse.gov for the Biden-Harris Administration.

Coding's a Drag
Anna Lytical
Developer Experience Engineer
Google 
https://share.getcloudapp.com/yAuy4Z6W
Anna Lytical is a "sickeningly entertaining" coding drag queen who creates fun and educational coding content to engage a young LGBTQ+ audience on TikTok, Twitter, YouTube, and beyond. When not inspiring the next generation of developers with their tutorials and videos, Anna Lytical works at Google as a Developer Experience Engineer. 

Taking Back the Internet — Community, Connection, & Code
Ben Halpern
Chief Creative Officer & Founder
Forem
https://share.getcloudapp.com/d5uRbPgL
Ben Halpern is a full stack developer, and the co-founder of and Chief Creative Officer of Forem: the open source community software powering dev.to, CodeNewbie Community, and many others. Every day, Ben goes to work and gets to help make the Internet a more inclusive and constructive place – he can't imagine doing anything else.
