### ISSUE TITLE
Use imgix for image optimization/transformation

### ISSUE THREAD

**Issue by danieltott** [code-newbies/codeland#67]
[imgix](https://imgix.com/) is really the best service for serving resized and optimized images on the fly. It has a free tier that should handle most of the needs of the marketing sites I've been working on (forem.com and codelandconf) and will greatly simplify both development and build time while having large positive effect on performance and speed (and therefore SEO as well).

If that's ok, I can get it set up - but not really sure who to look for for signoff on this sort of thing.

CCing @nickytonline @benhalpern - obviously add anyone else that should look and/or any questions here.

**Comment by nickytonline** [comment]
I think this makes sense. In terms of the account for imgix, we'd need to set it up with a Forem email account, or would yo@dev.to make more sense @benhalpern. That appears to be the default we use for a lot of things.

Also, just bringing up Cloudinary again as we have an account already. I know Cloudinary does much more than image resizing, but just wanted to see if we wanted to keep it all under that before we make a decision on moving to imgix.

**Comment by danieltott** [comment]
@nickytonline I forgot there's a DEV cloudinary account. It's a lot harder to deal with (and much more expensive) but it also can do a lot with video and stuff like that. I'd say though if I can have access to cloudinary I probably could set up similar things as what I had planned with imgix.

**Comment by nickytonline** [comment]
As discussed on Zoom @danieltott, go ahead and create the imgix account to apply the transformations.
