### ISSUE TITLE
Add sponsor graphics to site 

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#78]
## Requests

- Add clickable sponsor logos to `Sponsors` section on codelandconf.com. 
- Preserve existing `Sponsors` inquiry info, but move to a different section or relabel existing navigation as `Become a Sponsor`

## Details

- In the comments below, @SGGregory will add sponsor logo files, names (if we need to display text), sponsorship levels (if needed), and the external link they should lead to as this information becomes available. 
- We want to preserve the current sponsorship info section for other companies that want to join. Perhaps it should be labeled differently, however (ex: existing content `Become a Sponsor` whereas the logos could go under the current navigation label of `Sponsors`)
- Sponsorship-tier ordering request: Patron, Mentor, Inclusion, Technology, DEV Platform Sponsorship, Lightning Talk, Podcast, Featured Panelist (logos of sponsors should be listed according to their category in this order, with the patron sponsors featured the most prominently)

## Checklist 
_(please check off once sponsor is visible on the site. This list will be added to as we receive materials)_

- [x] Strapi
- [x] Stream
- [x] Storybook

**Comment by SGGregory** [comment]
## Strapi

**Name:** Strapi
**External Link:** https://strapi.io/careers?utm_source=event&utm_medium=codeland
**Logo:** 
<img width="763" alt="Strapi" src="https://user-images.githubusercontent.com/69541346/134223904-55a21ff6-ed47-47a0-bf88-431e116b1879.png">

**Comment by SGGregory** [comment]
## Stream

**Name:** Stream
**External Link:** https://getstream.io/?utm_source=codeland&utm_medium=event&utm_content=developer&utm_campaign=09_23_2021&utm_term=virtual
**Logo:**
![Stream Official Stacked](https://user-images.githubusercontent.com/69541346/130869350-416b3481-cebc-4c62-bebd-ad64b4b5e9db.png)


_^ this is the logo we have for them but it seems pretty small to me. Let me know if a larger file is needed._

**Comment by SGGregory** [comment]
@benhalpern I am going to use this issue as our ticketing system for adding sponsor logos to the site (as we receive them).  Let me know if this process doesn't work for you. 

@nickytonline @danieltott heads up that Ben and I have already had a discussion about him running point on adding sponsors.

**Comment by benhalpern** [comment]
@SGGregory I added Strapi and Stream to the site, but I didn't have access to that airtable, so I requested it. In the meantime I just linked to the home page and added just the image...

**Comment by SGGregory** [comment]
> @SGGregory I added Strapi and Stream to the site, but I didn't have access to that airtable, so I requested it. In the meantime I just linked to the home page and added just the image...

@benhalpern  Apologies! I changed the links above to the actual ones they sent instead of the Airtable record where it's listed (error on my part)

**Comment by SGGregory** [comment]
@benhalpern 

**Name:** StoryBlok
**External Link:** https://www.storyblok.com/?utm_source=codeland&utm_medium=logo&utm_campaign=codeland2021
**Logo:** ![colored-full](https://user-images.githubusercontent.com/69541346/131401327-2e7251c5-5c77-4265-9ef9-c615ab5f0bba.png)

**Comment by benhalpern** [comment]
Done with everything so far, keep 'em coming. @SGGregory

**Comment by SGGregory** [comment]
@benhalpern 

**Name:** Cockroach Labs
**External Link:** https://www.cockroachlabs.com/?utm_campaign=event-codeland&utm_source=codeland&utm_medium=event&utm_content
**Logo:** ![Cockroach Labs](https://user-images.githubusercontent.com/69541346/131754016-629e906a-b4b4-462a-bbf3-ded678baa507.png)

**Comment by SGGregory** [comment]
@benhalpern 

**Name:** Azure
**External Link:** https://aka.ms/Azure/Free
**Logo:** ![MS-Azure_logo_stacked_c-gray_rgb](https://user-images.githubusercontent.com/69541346/132790723-b3043937-687b-489f-92ab-e7f91bedb830.png)

**Comment by SGGregory** [comment]
@benhalpern could this one appear first (and if it's doable, could it be more prominent than the others, somehow — since they are our Patron Sponsor?)

**Name:** GitHub
**External Link:** https://github.com/about/careers
**Logo:** ![GitHub_Logo (1)](https://user-images.githubusercontent.com/69541346/134223830-dc8f8a38-7125-431d-ad11-5fb40439f7f1.png)

**Comment by SGGregory** [comment]
**Name:** Devocate
**External Link:** https://www.devocate.com/
**Logo:** ![2020-logo-website](https://user-images.githubusercontent.com/69541346/133307258-5cc88c4a-878a-4fb8-9bfc-db521abce473.png)

@benhalpern

**Comment by benhalpern** [comment]
✅

**Comment by SGGregory** [comment]
**Name:** Ionic
**External Link:** https://ionicframework.com/?utm_source=partner&utm_medium=referral&utm_campaign=codeland2021
**Logo:** ![ionic-logo](https://user-images.githubusercontent.com/69541346/133913899-28e2a4df-dbf3-4a67-998e-cf963f35c0bd.png)

@benhalpern

**Comment by SGGregory** [comment]
**Name:** New Relic
**External Link:** https://newrelic.com/
**Logo:** ![New Relic Logo](https://user-images.githubusercontent.com/69541346/134092123-464fac41-8809-4486-966f-0af06cd81092.png)


### @benhalpern note that New Relic is our other patron sponsor so we should feature them up top with GitHub

**Comment by SGGregory** [comment]
**Name:** Commsor
**External Link:** http://commsor.com/
**Logo:** ![commsor-logo](https://user-images.githubusercontent.com/69541346/134260456-6033651a-6f28-4a72-8c1b-0adc684bb20d.png)
@benhalpern

**Comment by SGGregory** [comment]
**Name:** Sourcegraph
**External Link:** https://about.sourcegraph.com/
**Logo:** ![sourcegraph-logo](https://user-images.githubusercontent.com/69541346/134260348-09a17a8b-a224-4b33-8ddc-8641e9511f8d.png)


@benhalpern

**Comment by SGGregory** [comment]
**Name:** Typesense
**External Link:** https://typesense.org
**Logo:** ![typesense](https://user-images.githubusercontent.com/69541346/134092636-03533695-92bc-44e5-b424-33d0e19c6977.png)

@benhalpern

**Comment by SGGregory** [comment]
**Name:** AWS
**External Link:** https://aws.amazon.com/
**Logo:** ![1200px-Amazon_Web_Services_Logo svg](https://user-images.githubusercontent.com/69541346/134223661-a0d95fde-4a41-4326-9ff4-bd81cf71c081.png)

@benhalpern

**Comment by SGGregory** [comment]
@benhalpern just a note that Strapi and GitHub have also updated their logos. Files above.

**Comment by SGGregory** [comment]
@benhalpern sorry to do this, but Sourcegraph and Commsor have updated their logos. Files above.
