### ISSUE TITLE
Update Marketing Website for 2022 CodeLand Announcement 

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#91]
# Description of Task

We'll need to update the CodeLand marketing site (codelandconf.com) in preparation for our CodeLand 2022 announcement on March 1, 2022. We'll want to replace all mentions of 2021 with 2022 and remove sections that aren't relevant to the current event-planning juncture we're at. 

Very basic wireframe for each page is within each section. All graphics requested can be found [here](https://drive.google.com/drive/folders/13bVBfMLUdeN-rTtVYWj0MhsQ-bcCzQzk?usp=sharing).

### Update Top Menu Bar

- [x] Remove `Program` and replace with `Submit a Talk` which leads to CFP site: https://cfp.codelandconf.com/events/codeland-2022 (open in external page)
- [x] Change `Sponsors` to `Sponsorship`
- [x] Change `CodeLand 2020` to `CodeLand 2021` which should like to https://community.codenewbie.org/codeland

### Update Home Fold

- [x] Replace CodeLand Logo with 2022 version
- [x] Add screenshots 1&2 to lefthand side (as shown in wireframe image)
- [x] Add screenshot 3 to righthand side (as shown in wireframe image)
- [x] **Replace text:** `Taking place virtually from` with `Taking place virtually on`
- [x] **Replace text:** `September 23-24, 2021` with `June 16 & 17, 2022`
- [x] **Replace text (button):** `Register Now` with `Submit a Talk` (link to "Submit a Talk" section)
- [x] Add CodeNewbie logo where indicated on wireframe

![home-fold-wireframe](https://user-images.githubusercontent.com/69541346/155275232-4a368f81-da07-4a44-921b-09df287367f7.jpg)

### Update Transitional section between Home Fold and `Attend` section

- [x] **Replace text:** `Motivating talks, rewarding activities, and connection with other code-obsessed people like you.` with `Motivating talks, rewarding activities, and connection with other coding-obsessed people like you.`
- [x] Replace lefthand screenshot with screenshot 4

![transitional-fold](https://user-images.githubusercontent.com/69541346/155275408-0a00f40c-853e-42ff-ba89-6117e64122c6.jpg)

### Update `Attend` Section

- [x] **Replace text:** `CodeLand 2021 is an entirely remote two-day conference. Each day will be six hours long (9am-3pm PT / 12-6pm ET / 4-10pm UTC) and will consist of a mix of live keynotes, live speaker panels, pre-recorded talks, and optional add-on workshops on both days.`. with `CodeLand 2022 is an entirely remote two-day conference. Each day will be six hours long (9am-3pm PT / 12-6pm ET / 4-10pm UTC) and will consist of a mix of keynotes, live speaker panels, pre-recorded talks, and engaging activities.`
- [x] Update `Registration` Copy with: `Return here on April 26, 2022 to grab your ticket!`
- [x] Update `Cost` Copy with: `CodeLand 2022 is pay-what-you-want — starting at $0.`

![attend](https://user-images.githubusercontent.com/69541346/155275493-7d03f522-6f2f-4b7e-90ba-ac6ba6991f62.jpg)

### Update `Sponsors` Section

- [x] Rename section to `CodeLand 2022 Sponsorship`
- [x] Remove 2021 sponsor logos and sections
- [x] Replace `Interested in joining other tech thought-leaders in supporting CodeLand? Want to share your service or product with a global audience of developers? Fill out our form for more information on sponsorship opportunities.` with `Interested in joining other tech thought-leaders in supporting CodeLand? Want to share your service or product with a global audience of developers? Fill out the form for more information on our sponsorship opportunities.`
- [x] Replace 2021 embedded sponsorship brochure form with 2022 sponsorship brochure form code (HTML available [here](https://docs.google.com/document/d/1okH8-r_SwW6AF_JLBIdgBq5najwwdZ6V278i_LtUq4w/edit?usp=sharing) )
- [x] **Replace form description text:** `Not seeing our sponsorship form? Click [this link](https://codenewbie.us8.list-manage.com/subscribe?u=0a92a565e5b5037722c845fdb&id=7736126f21) or try [disabling tracking protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_what-to-do-if-a-site-seems-broken) if you're using Firefox.` with `Not seeing our sponsorship form? Click [this link](http://eepurl.com/hVuRx1) or try [disabling tracking protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_what-to-do-if-a-site-seems-broken) if you're using Firefox.`

![sponsors](https://user-images.githubusercontent.com/69541346/155275624-32c3fab3-4a50-4c1f-80c3-8696e6b4f66d.jpg)

### Add `Submit a Talk` Section

The CodeLand call-for-proposals is open from March 1-March 29, 2022. Our program committee looks forward to reviewing your talk geared at inspiring and educating early-career software developers and their champions. Find full instructions and submit your proposal [here](https://cfp.codelandconf.com/events/codeland-2022)

### Update footer

- [x] Replace logo with 2022 version
- [x] **Replace text:** `Produced by [DEV](https://dev.to/) and [CodeNewbie](https://community.codenewbie.org/).` with `Brought to you by [Forem](https://forem.com).`
- [x] Update text: `Fill out our interest form above to receive a copy of the CodeLand sponsorship brochure — or email us at [sponsors@forem.com](mailto:sponsors@forem.com) for more info.` with `Fill out our interest form above to receive a copy of the CodeLand sponsorship brochure — or email us at [sponsors@forem.com](mailto:sponsors@forem.com) for more information.`
- [x] Change contact email to codeland@codeland.org. 

![footer](https://user-images.githubusercontent.com/69541346/155275718-34fa40b2-938d-4fe1-9636-74566f764115.jpg)

### Update Accessiblity Statement

- [x] Update year from 2021 to 2022
- [x] Update text: From `As such, we are ensuring that keynotes contain live captions and pre-recorded talks contain closed captions for anyone who may find them useful.` to `As such, we are ensuring that all talks contain closed captions for anyone who may find them useful.`

### Update FAQs

- [x] Update year from 2021 to 2022
- [x] Update text: From `For the second year in a row, all CodeLand activities will be virtual in 2021.` to `For the third year in a row, all CodeLand programming will be virtual.`
- [x] Update text: From `Our on-demand talks will be selected from submissions to our CFP (link), which opens on June 22.` to `Our non-keynote talks will be selected from submissions to our [CFP](https://cfp.codelandconf.com/events/codeland-2022), which is open from March 1, 2022 to March 29, 2022.`

**Comment by SGGregory** [comment]
@danieltott here's the issue for the Marketing Site updates!

**Comment by danieltott** [comment]
@SGGregory  https://deploy-preview-92--codelandconf.netlify.app/ 

Got those changes up! 

Take a look at the new design elements - made some best guesses for the screenshots and the new logo sticker.

For the sticker it might be better to sort of squash them all together under the button, but you can let me know what you think 👍

**Comment by abbyphoenix** [comment]
Okay, really interesting split here between the mobile and desktop look. 

For **desktop**, the screenshots from last year are on the side of the logo and two overlap each other. 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/4975727/155772222-795b6eab-77d0-4a62-a99c-d05974858599.png">

For **mobile**, they're in a horizontal grid below the logo and are each fully visible. 
<img width="200" src="https://user-images.githubusercontent.com/4975727/155772376-085e4697-5f5d-4168-9309-535bb102aa71.jpeg">
 
Honestly, I'm wondering if we can do something different here, where we put the images (in both desktop and mobile, ideally) in a grid like it is on mobile, but **across the top between the nav bar and the logo**? There's a lot of white space there (it's there in mobile too, but I had to scroll down past it to show the screenshot images), and it'd be nice to fill it with those if possible?

**Comment by abbyphoenix** [comment]
If we keep the screenshots where they are, I'd like to see if we can reduce this white space and bring everything up?


<img width="600" alt="Screen Shot 2022-02-25 at 11 19 40 AM" src="https://user-images.githubusercontent.com/4975727/155775143-565dbffe-1109-49fd-8be1-9bbb57a5e196.png">

**Comment by abbyphoenix** [comment]
### Quick Hits

**Sponsorship**
- Let's reword Sponsorship Brochure as "Sponsorship Prospectus"
- I wonder if we should even include Patron (actually, it's not listed here, but it is when you click the "this link"), Thought-Leader, or Mentor levels here since there's no way anyone could know what that means? Actually, thinking this through... before someone sees the prospectus, how would they know what _any_ of these terms mean? Do we even need to ask this at this point, or **could we remove this whole Level of Interest column**? @SGGregory 
- At the "this link" link, can we change Brochure to Prospectus?

**Submit a talk**
- Can we capitalize Call-For-Proposals and Program Committee?

**Footer**
- The Twitter link says it's for [@codelandconf](https://twitter.com/codelandconf) but takes you to the account for [@codenewbies](https://twitter.com/codenewbies), so we should change the link
- I have honestly no idea where that email would go, I don't think we own "codeland@codeland.org" 😉  It should be codeland@codenewbie.org

**Comment by abbyphoenix** [comment]
Surprisingly 😂, I have no opinion on where the stickers are placed -- they look good to me, but I can see them squished under the button too!

**Comment by danieltott** [comment]
@abbyphoenix for the screenshots we can do any of that - just let me know what you want 👍

**Comment by SGGregory** [comment]
- Sticker placement looks good to me!
- I'm good to put the screenshots in a line. I will note that they look very small in the current format so I'm wondering if the same will be true if we move them into a line, but perhaps we can't avoid that due to resolution. 
- Good point, Abby. I'll remove the checkboxes from the MailChimp form. That was a residual decision from last year but perhaps it didn't make sense then either lol 
- Everything else looks good to me! Abby nabbed all of my feedback 😉 

Nice job!

**Comment by SGGregory** [comment]
This might not be necessary, but just in case, here's the updated sponsorship form HTML (without tier checkboxes): 

```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://codelandconf.us8.list-manage.com/subscribe/post?u=0a92a565e5b5037722c845fdb&amp;id=406a7a70a1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE3">Organization  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="MMERGE3" class="required" id="mce-MMERGE3">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0a92a565e5b5037722c845fdb_406a7a70a1" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='MMERGE3';ftypes[3]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
```

**Comment by abbyphoenix** [comment]
@danieltott Let's try in a line above CodeLand! How big can we make them? 👀

**Comment by danieltott** [comment]
@abbyphoenix we can make them as big as the width of the browser window divided by three if that’s what we want. I promise I can do anything you want - you just tell me what to do 😁

**Comment by abbyphoenix** [comment]
Awesome! Let's go with the width of the nav bar, divide by three, but then add in padding all around, like 10px? (is that even how it's measured?)

**Comment by danieltott** [comment]
@abbyphoenix @SGGregory Those changes are up on the staging site: https://deploy-preview-92--codelandconf.netlify.app/

I tried out a little designy stuff for the screenshots - let me know if they work or if you want to see them more regular (:

**Comment by abbyphoenix** [comment]
I like this! Including the designer-y stuff! 👍🏽👍🏽

I looked on mobile and it looks the same too, which I like -- there is an issue with the content width on mobile, but otherwise, it's all looking ready to me!

**Comment by danieltott** [comment]
@abbyphoenix what issue are you seeing?

**Comment by abbyphoenix** [comment]
I can pinch to zoom out and see more whitespace:
<img src="https://user-images.githubusercontent.com/4975727/156045110-cc7f605e-0295-4e36-ba4b-c7950b39a2ae.jpeg" width="300">

And then when I open the menu, it widens too far to the point where I can't get to the last options:
<img src="https://user-images.githubusercontent.com/4975727/156045099-fa5663f5-7e9f-44c9-befa-ead0b2971912.jpeg" width="300">

Which is an issue that persists when when I manually zoom back in:
<img src="https://user-images.githubusercontent.com/4975727/156045147-622ae972-fdba-44fd-aee4-bff96a140916.jpeg" width ="300">

**Comment by danieltott** [comment]
@abbyphoenix Thanks - both of those have been fixed 👍

**Comment by danieltott** [comment]
@abbyphoenix @SGGregory This is ready to go live whenever you're ready - just let me know.

**Comment by abbyphoenix** [comment]
@danieltott Gorgeous, I love it!! 

One clarification: the CFP link at "here" under Submit a talk will go to the correct one once this has been pushed live, right?

@SGGregory -- take a look when you get a moment, but it's looking good to me!

**Comment by SGGregory** [comment]
@danieltott Beautiful. LOVE what you did with the screenshots. Really clean. This is good to ship, pending the question @abbyphoenix  asked above 🎉

**Comment by danieltott** [comment]
@SGGregory @abbyphoenix ok, fixed that link, and all changes are live!

![go time](https://media.tenor.com/images/1d9874c34e2b1e2826851a9cdeea8b22/tenor.gif?ver=0126&c=VjFfZnJhbms)
