### ISSUE TITLE
Change website card to reflect current year

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#93]
## Description of issue

Currently, the social card attached to the website is outdated. When the site is shared on social media, the old card appears. [See example](https://share.getcloudapp.com/mXuY7dKz)

## Request

Request to update CodeLandConf.com social card with the image below:
![codelandconf com](https://user-images.githubusercontent.com/69541346/158491267-ea816fe6-e253-4ae3-8054-ff0c274b0b8b.png)

Thank you!

**Comment by danieltott** [comment]
@SGGregory This is live! https://codelandconf.com/

**Comment by SGGregory** [comment]
Thank you!
