### ISSUE TITLE
Update CodeLand Marketing Site Post CFP-Deadline

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#96]
We'll need to update the CodeLand marketing site (codelandconf.com) after the CFP deadline passes on March 29 @ 4:49 PM PT/11:59 PM UTC. Here are the necessary tasks to update the site:

- [ ] Replace `Submit a Talk`  top menu button with `Talk Info`
- [ ] Remove `Submit a Talk` button from hero
- [ ] Edit "Submit a Talk" website section with the following copy;

[Heading] Talk Info

[Sub-heading/body 1] The magic of CodeLand lies in our fantastic talks from a diverse group of speakers — from the CodeNewbie Community and beyond! No two talks will be alike, but together, they’ll be inspiring and packed with practical information.

[Sub-heading/body 2, italics] _The CodeLand Call-For-Proposals closed on March 29, 2022. Our Program Committee is currently reviewing submissions and we'll be announcing selections in the coming weeks. If you submitted a talk, please monitor your email for communications from our team about the status of your proposal._

**Comment by SGGregory** [comment]
@danieltott heads up about this request. Thank you in advance :) Today is the day of the CFP deadline so it would be great to have this update as soon as possible. Thank you!

**Comment by danieltott** [comment]
@SGGregory This is live!
