### ISSUE TITLE
Update CodeNewbie Logo from Green Version to Purple Version

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#98]
We updated the CodeNewbie brand colors from green to purple and will need to update the CodeNewbie logo on our marketing site's footer. Updated/correct version attached!

Thanks so much 😊 Let me know if anything else is needed here. 

![codenewbie-full-outlined](https://user-images.githubusercontent.com/69541346/162083646-164dda80-9f6f-4cfa-89fd-f4665b76dfa6.png)

**Comment by danieltott** [comment]
@SGGregory do you have a transparent and/or vector version of this image?

**Comment by SGGregory** [comment]
> 

Here you go @danieltott  😊
![codenewbie-full](https://user-images.githubusercontent.com/69541346/165631314-f8c776f7-307a-4d3a-bf83-347a252f2b29.svg)

**Comment by danieltott** [comment]
LIVE
