### ISSUE TITLE
Update Marketing Site For Angie Jones Announcement 

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#99]
# Description of Task

We're announcing our first CodeLand Keynote speaker on April 19, 2022 around 9:30 AM PT

It would be fantastic if we could feature Angie on the site following the announcement in the ways described below. 

### Update `Talk Info` section:

- [ ] Add an outlined or color background text box between the existing unitalicized text and the italicized text in this section:
- Angie Jones' headshot on the left of the box. File [here](https://user-images.githubusercontent.com/69541346/163855032-0748b9cc-0a10-485f-8a49-01e5cf68dccc.jpg).
- Heading: Keynote Speaker Announcement!
- Sub-heading: We've announced our first CodeLand keynote speaker: Angie Jones.
- C2A: [Learn more here] (link to be provided)
- 
### Add a small banner or popup at the top of the site linking to our Angie Jones announcement post

- [ ] Text should say: 
- [Heading] Angie Jones Has Been Announced as CodeLand 2022's First Keynote Speaker. 
- [sub-heading/C2A, italicized] Learn more [here] (link to be provided)

## Requested deadline

Tuesday, April 19 following our announcement. Gracie will provide link once it's live, around 9:30 AM PT.

**Comment by danieltott** [comment]
@SGGregory A preview for this is up: https://deploy-preview-100--codelandconf.netlify.app/

Let me know if you have any changes!

**Comment by SGGregory** [comment]
Looks great! Here's the live link: https://community.codenewbie.org/codenewbie/announcing-codeland-2022s-first-keynote-speaker-angie-jones-1gn8 Ready to ship 😊

**Comment by danieltott** [comment]
@SGGregory live! https://codelandconf.com/
